version: '3'
services:
  postgres:
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
  redis:
    image: redis:4.0-alpine
    ports:
      - 6379:6379
  memcached:
    image: memcached:1.5-alpine
    ports:
      - 11211:11211
