version: 2
jobs:
  install_ruby_dependencies:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
    working_directory: ~/spark-starter-kit
    steps:
      - checkout
      - restore_cache:
          keys:
            - ruby-dependencies-v6-{{ checksum ".ruby-version" }}-{{ checksum "Gemfile.lock" }}
            - ruby-dependencies-v6-{{ checksum ".ruby-version" }}
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: Set bundle path
          command: bundle config --local path vendor/bundle
      - run:
          name: Bundle Install
          command: |
            bundle check || bundle install --deployment
      - save_cache:
          paths:
            - vendor/bundle
          key: ruby-dependencies-v6-{{ checksum ".ruby-version" }}-{{ checksum "Gemfile.lock" }}

  install_javascript_dependencies:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
    working_directory: ~/spark-starter-kit
    steps:
      - checkout
      - restore_cache:
          keys:
            - javascript-dependencies-v3-{{ checksum "yarn.lock" }}
            - javascript-dependencies-v3
      - run:
          name: Which yarn?
          command: yarn -v
      - run:
          name: Install Yarn
          command: yarn install --ignore-engines
      - save_cache:
          paths:
            - node_modules
          key: javascript-dependencies-v3-{{ checksum "yarn.lock" }}

  run_tests:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
      - image: postgres:10.4
    working_directory: ~/spark-starter-kit
    steps:
      - checkout
      - restore_cache:
          keys:
            - ruby-dependencies-v6-{{ checksum ".ruby-version" }}-{{ checksum "Gemfile.lock" }}
            - ruby-dependencies-v6-{{ checksum ".ruby-version" }}
      - restore_cache:
          keys:
            - javascript-dependencies-v3-{{ checksum "yarn.lock" }}
            - javascript-dependencies-v3
      - run:
          name: Set bundle path
          command: bundle config --local path vendor/bundle
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432
      - run:
          name: Setup DB
          command: bundle exec rails db:create db:schema:load
      - run:
          name: Run Rspec
          command: bundle exec rspec

workflows:
  version: 2
  main:
    jobs:
      - install_ruby_dependencies
      - install_javascript_dependencies
      - run_tests:
          requires:
            - install_ruby_dependencies
            - install_javascript_dependencies
