version: 2
jobs:
  install_ruby_dependencies:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
    working_directory: ~/spark-starter-kit
    steps:
      - checkout
      - restore_cache:
          keys:
            - ruby-dependencies-v6-{{ checksum "Gemfile.lock" }}
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: Bundle Install
          command: |
            bundle check || bundle install --deployment
      - save_cache:
          paths:
            - vendor/bundle
          key: ruby-dependencies-v6-{{ checksum "Gemfile.lock" }}

  install_javascript_dependencies:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
    working_directory: ~/spark-starter-kit
    steps:
      - checkout
      - restore_cache:
          keys:
            - javascript-dependencies-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Install Yarn
          command: yarn install --ignore-engines
      - save_cache:
          paths:
            - node_modules
          key: javascript-dependencies-v1-{{ checksum "yarn.lock" }}

  run_rubocop:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
    working_directory: ~/spark-starter-kit
    steps:
      - checkout
      - restore_cache:
          keys:
            - ruby-dependencies-v6-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          keys:
            - javascript-dependencies-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Set bundle path
          command: bundle config --local path vendor/bundle
      - run:
          name: Rubocop Check
          command: bundle exec rubocop || true

  run_reek:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
    working_directory: ~/spark-starter-kit
    steps:
      - checkout
      - restore_cache:
          keys:
            - ruby-dependencies-v6-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          keys:
            - javascript-dependencies-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Set bundle path
          command: bundle config --local path vendor/bundle
      - run:
          name: Reek Check
          command: bundle exec reek || true

  run_brakeman:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
    working_directory: ~/spark-starter-kit
    steps:
      - checkout
      - restore_cache:
          keys:
            - ruby-dependencies-v6-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          keys:
            - javascript-dependencies-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Set bundle path
          command: bundle config --local path vendor/bundle
      - run:
          name: Brakeman Check
          command: bundle exec brakeman --skip-files vendor/bundle/

  run_tests:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
      - image: postgres:10.4
    working_directory: ~/spark-starter-kit
    steps:
      - checkout
      - restore_cache:
          keys:
            - ruby-dependencies-v6-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          keys:
            - javascript-dependencies-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Set bundle path
          command: bundle config --local path vendor/bundle
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432
      - run:
          name: Setup DB
          command: bundle exec rails db:create db:schema:load
      - run:
          name: Run Rspec
          command: bundle exec rspec

workflows:
  version: 2
  main:
    jobs:
      - install_ruby_dependencies
      - install_javascript_dependencies
      - run_rubocop:
          requires:
            - install_ruby_dependencies
      - run_reek:
          requires:
            - install_ruby_dependencies
      - run_brakeman:
          requires:
            - install_ruby_dependencies
      - run_tests:
          requires:
            - install_ruby_dependencies
            - install_javascript_dependencies
